--- #YAML:1.0
name:               Test-MobileAgent
version:            0.02
abstract:           set environmental variables to mock HTTP::MobileAgent
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Headers::Fast:  0
    HTTP::MobileAgent:    0.28
    List::Util:           0
    Test::More:           0.88
    Test::UseAllModules:  0.10
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
